### ISSUE TITLE
Залить в папку www

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#12]
залить все файлы репозитория в папку www для упрощения дальнейшей работы с ними через денвер

**Comment by AndruAlex** [comment]
что за задиние в папку www 
а если кто то вампом или ксампом пользуеться ?

**Comment by nikolayr1** [comment]
все пользуются денвером кроме тебя

**Comment by AndruAlex** [comment]
)ну окей
