### ISSUE TITLE
dry code

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#13]
Сделать html файлы php-шными и подключать в них элементы повторяющиеся элементы страниц (header footer calculator ...)

**Comment by Wilvarin** [comment]
.phtml

**Comment by AndruAlex** [comment]
а смысл если все будет натягиваться на уии и там это реализовано по другому?

**Comment by AndruAlex** [comment]
ты же имеешь в виду что если калькулятор есть и на главной и на сранице партнерев то 
вынести калькулятор в отдельный файл и подключить инклюдом?

**Comment by nikolayr1** [comment]
да. потому, что ты, например поправишь хедер и калькулятор на главной и тебе придется поправлять хедеры и калькуляторы в каждом файле, если ты не будешь подключать их инклюдом.

**Comment by Wilvarin** [comment]
да он потом хедер и футер просто в лояут внесет, а калькулятор сделает виджетом.

**Comment by nikolayr1** [comment]
потом да, но пока что ему придется переправлять их в каждом хтмл документе. если ему не сложно это делать - то пожалуйста
