### ISSUE TITLE
Фильтры 

### ISSUE THREAD

**Issue by AndruAlex** [TopQualityGuys/ecoenergie#132]
- [x] пунк стоимость 
https://pp.vk.me/c630826/v630826993/26784/ngxi2xwcuYw.jpg

- [x] проверить крайние границы ВСЕХ ФИЛЬТРОВ

- [x] Аккумуляторы не выводиться тип в фильтрах

- [x] Контроллеры номинальный зарядный ток АКБ в АМПЕРАХ

**Comment by AndruAlex** [comment]
https://pp.vk.me/c630826/v630826993/2677a/L4S9TApMBrE.jpg
https://pp.vk.me/c630826/v630826993/26770/78bfclc6Ssk.jpg
https://pp.vk.me/c630826/v630826993/26766/hxvGFZNQ9bg.jpg
https://pp.vk.me/c630826/v630826993/26752/YxGDvG6wjs8.jpg
https://pp.vk.me/c630826/v630826993/2673e/sVAoT7XJhLQ.jpg
https://pp.vk.me/c630826/v630826993/26748/dDK2HltiO_c.jpg
https://pp.vk.me/c630826/v630826993/26784/ngxi2xwcuYw.jpg

**Comment by dumbik** [comment]
ебанутые цены
![image](https://cloud.githubusercontent.com/assets/11014944/14762480/f28ba8d2-0983-11e6-87ad-dbfc896dd044.png)

**Comment by dumbik** [comment]
- [ ]  зачем нужен фильтр напряжения АКБ![image](https://cloud.githubusercontent.com/assets/11014944/14762555/06904228-0986-11e6-9ab5-bfd7f603c66d.png)

- [ ] как изменить выделенный текст (убрать запятую)
![image](https://cloud.githubusercontent.com/assets/11014944/14762569/45446d6e-0986-11e6-964e-974889f5b3a3.png)
