### ISSUE TITLE
Баг верстки

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#147]
![default](https://cloud.githubusercontent.com/assets/11279857/15758129/d436d53e-2911-11e6-8815-d994b8396bb7.png)

**Comment by dumbik** [comment]
И здесь (нет отступов)

![image](https://cloud.githubusercontent.com/assets/11014944/15802927/353ef8ea-2acd-11e6-94dd-1a78a757ca15.png)

**Comment by AndruAlex** [comment]
Мною баг не был обнаружен так что закрываю задачу.

**Comment by nikolayr1** [comment]
@AndruAlex ок

**Comment by dumbik** [comment]
![image](https://cloud.githubusercontent.com/assets/11014944/15980201/2e2c797a-2f72-11e6-8624-5f73b85778b7.png)

**Comment by dumbik** [comment]
хоть бы отписывал, когда задачи переоткрывают. пиздец.
