### ISSUE TITLE
пофиксить верстку калькулятора (страница готовых решений)

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/ecoenergie#150]
![image](https://cloud.githubusercontent.com/assets/11014944/15802603/460a0f50-2ac0-11e6-9313-c278c77fbaeb.png)

**Comment by nikolayr1** [comment]
![default](https://cloud.githubusercontent.com/assets/11279857/15867105/3d47de52-2cea-11e6-84c1-75974d52cb10.png)
Страница акций.
