### ISSUE TITLE
Форма обратной связи не очищается после отправки

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#151]
Браузер мозила
Страница http://ecoenergie.com.ua/contact
Не очищается форму после отправки. Возможны дубли отправок, сбой в подсчете конверсий и настройке рекламной кампании.
Вообще уже чинили очистку формы, но получается, что нужно еще раз все починить и проверить все ли формы очищаются после отправки.

**Comment by AndruAlex** [comment]
Стой
