### ISSUE TITLE
css 3 :target

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#23]
Удалить это js порно и сделать это на css. В других местах скрипта тоже делать цссом, если это возможно.
![image](https://cloud.githubusercontent.com/assets/11279857/13146836/0f33f90a-d660-11e5-8b64-8c25890073da.png)

**Comment by AndruAlex** [comment]
target не подходит 
поскольку таргетом не возможно реализовать такие возможности

**Comment by nikolayr1** [comment]
таргетом можно реализовать смену цсс свойств при нажатии на элемент. почему ты считаешь, что здесь таргет не подойдет?

**Comment by AndruAlex** [comment]
потому что сдесь не только цсс меняется и таргет реализовует смену цсс 1 блока при назатии на другой это на сколько я понял с описания

**Comment by nikolayr1** [comment]
сдесь действия производятся над дочериными элементами. Это делается таргетом
