### ISSUE TITLE
при уменьшении экрана текст на слайдере залезает под меню

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/ecoenergie#4]
![image](https://cloud.githubusercontent.com/assets/8439283/12990446/1ca707d2-d113-11e5-9057-43bc32a19bd9.png)

**Comment by AndruAlex** [comment]
Дела говно потому что на моб версии он там никак не влезет
может его вообще на моб версии скрывать?

**Comment by dadakax** [comment]
в смысле не влезет?
