### ISSUE TITLE
Перевести на русский админку 

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/ecoenergie#47]
перевести названия модулей и все надписи в админке

**Comment by nikolayr1** [comment]
и убрать надпись easyiicms

**Comment by dadakax** [comment]
@nikolayr1 , а зачем?

**Comment by nikolayr1** [comment]
@dadakax ,чтобы все было качественно. помнится мне, что Стас просил меня убрать надписть easycms в укрзализныце.

**Comment by dadakax** [comment]
@nikolayr1 это потому что они не должны были знать что мы на цмске делаем. А экоенерджи вообще похер, цмска бесплатная
