### ISSUE TITLE
Создание подкатегорий

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#49]
Добавить поле "родительская категория" на странице создания новой категорий.
![image](https://cloud.githubusercontent.com/assets/11279857/13379531/686158f6-de30-11e5-8f05-01fa66e11d00.png)

**Comment by nikolayr1** [comment]
хм. понял как создавать подкатегории. вопрос закрыт

**Comment by dadakax** [comment]
Шта? А зачем?
![image](https://cloud.githubusercontent.com/assets/8439283/13381868/4aa164ac-de6f-11e5-988a-55afe17af0a9.png)
