### ISSUE TITLE
Ссылка на карточку товара

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#54]
Сделать весь блок товара на странице категории ссылкой на карточку этого товара. Сейчас на страницу карточки товара можно попасть нажав на крошечную кнопочку "Купить"
![image](https://cloud.githubusercontent.com/assets/11279857/13616745/e311bce4-e583-11e5-8b09-abf54f250325.png)

**Comment by dadakax** [comment]
сделала ссылкой картинку и заголовок.
