### ISSUE TITLE
список товаров ограничить размер картинки

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/ecoenergie#60]
![image](https://cloud.githubusercontent.com/assets/8439283/13627022/c5670f86-e5cf-11e5-85eb-1ca079b0fbdd.png)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/13669974/b52ead94-e6cf-11e5-9dbf-319db88624b6.png)
![image](https://cloud.githubusercontent.com/assets/11279857/13669979/bf99c494-e6cf-11e5-84f7-4e7a5360febe.png)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/13725403/5b5ae504-e8a9-11e5-9d04-82dc5c147e2f.png)
