### ISSUE TITLE
Смена категории товара

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#63]
Необходимо реализовать функцию смены категории товара. Это понадобится заказчикам в дальнейшем, когда они будут менять древо категорий

**Comment by dumbik** [comment]
изменены файлы:
![image](https://cloud.githubusercontent.com/assets/11014944/15805371/b3594a42-2b30-11e6-8316-dbcd268caebb.png)
![image](https://cloud.githubusercontent.com/assets/11014944/15805374/d3b0ce50-2b30-11e6-971b-bc273a98dd55.png)
![image](https://cloud.githubusercontent.com/assets/11014944/15805376/dc120866-2b30-11e6-8c75-92a5351999db.png)
