### ISSUE TITLE
Name поля

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#64]
Колонка name не имеет никакого смысла. Если ее оставить пустой и сохранить поля, то страница обновится, но новые поля не будут созданы. Эту колонку нужно обязательно заполнять - то есть делать бесполезную работу.
![image](https://cloud.githubusercontent.com/assets/11279857/13725429/1f9a7e48-e8aa-11e5-8ab1-361dd41e9cf5.png)

**Comment by dadakax** [comment]
????????????????????????????????????????????????????????????????7
КАКУЮ БЕСПОЛЕЗНУЮ РАБОТУ?????
Коль, по названию параметра потом в товары сохраняются значения. Это поле обязательное не зря
