### ISSUE TITLE
Страница пустой корзины

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#83]
- [x] Заменить надпись "Shopping cart is empty" на "Корзина пока пуста. Перейти на страницу категорий товаров"

- [ ] Сделать так, чтобы футер не отрывался от нижней границы экрана.
![image](https://cloud.githubusercontent.com/assets/11279857/13898305/f2a953da-eddd-11e5-82ee-fe5b13ef407d.png)

- [ ] Перевести надпись "Success. Your order successfully created. Our manager will contact you as soon as possible." и сделать ее читаемой
![image](https://cloud.githubusercontent.com/assets/11279857/13898455/6877f144-ede2-11e5-9023-5fe23de4f98d.png)

**Comment by dadakax** [comment]
надпись об успешном заказе переведена
![image](https://cloud.githubusercontent.com/assets/8439283/14065544/09a56614-f437-11e5-84ec-c3c6e418a420.png)
