### ISSUE TITLE
hover effect

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#84]
Добавить курсор поинтер при наведении на кнопку "добавить в корзину" на странице категории

**Comment by dumbik** [comment]
эта задача уже есть в полном списке "Задач от Антона". Просто она там не расписана. Кроме этого кнопке "подробнее" и кнопке "добавить в корзину" нужно задать одинаковые border-radius КАК В МАКЕТЕ, епта
