### ISSUE TITLE
Поле "Метка"

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#87]
- [x] переименовать поле "метка"->"url категории" и 

- [x] перенести "url категории" в блок seo
![image](https://cloud.githubusercontent.com/assets/11279857/13899057/824925d0-edf5-11e5-9bc8-29583de85d6f.png)

**Comment by dumbik** [comment]
переносить url в сео - неоправданный геморой, так как сео - идет отдельно от категории. 
переименовать - я переименую
