### ISSUE TITLE
Удалить поле Name 

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#88]
Сейчас на странице создания полей категории существует поле Name. Нужно его удалить, ведь оно не несет никакой смысловой нагрузки, но обязательно для заполнения.
![image](https://cloud.githubusercontent.com/assets/11279857/13899361/5b6c7568-edfd-11e5-926f-b377514b5a2d.png)

**Comment by dumbik** [comment]
Даша кажется уже писала по этому поводу. это поле нужно примерно для того, для чего нужен алиас или слаг, так что удалять его никто не будет
