### ISSUE TITLE
Не работают поля

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/ecoenergie#90]
- [x] Ссылка с ютуба, вставленная в поле видеоозора не добавляет видео на страницу товара

- [x] Поле типа checkbox работает некорректно 
![image](https://cloud.githubusercontent.com/assets/11279857/13899897/2a35fcc8-ee0a-11e5-8c49-9df0928bf6d0.png)
![image](https://cloud.githubusercontent.com/assets/11279857/13899898/2fa7ddf2-ee0a-11e5-9e87-d0ee239cd5fe.png)

**Comment by dumbik** [comment]
видео добавляется, ссылка вставляется следующим образом:
https://pp.vk.me/c629114/v629114763/4ac59/6iGNXPIqUZE.jpg

**Comment by dumbik** [comment]
кроме вьюхи был изменен контроллер в вендоре: 
![image](https://cloud.githubusercontent.com/assets/11014944/15802912/7da0e7c0-2acc-11e6-8a07-a08f9b5e57b6.png)

такое:
![image](https://cloud.githubusercontent.com/assets/11014944/15802916/8f3663ca-2acc-11e6-99fc-5f89186a1754.png)

выводится таким образом:
![image](https://cloud.githubusercontent.com/assets/11014944/15802917/99c71c44-2acc-11e6-8efc-e8f523f5514a.png)
