### ISSUE TITLE
Правки. Реализованные проекты

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/ecoenergie#93]
- [x] Выровнять текст по картинке 
![image](https://cloud.githubusercontent.com/assets/11739563/13914894/0c30a8d0-ef5a-11e5-9e98-afe78b679241.png)

- [x]  расстояние меду двумя длока проектов должно быть 50 пикс 
![image](https://cloud.githubusercontent.com/assets/11739563/13914940/3f079994-ef5a-11e5-8e11-102e2e82a44b.png)

- [x] вертикальные фотографии
![image](https://cloud.githubusercontent.com/assets/11739563/13914949/53c9408a-ef5a-11e5-89b5-c4ac363536c1.png)
![image](https://cloud.githubusercontent.com/assets/11739563/13915051/ffd9c3ea-ef5a-11e5-84be-27ff4965477c.png)

**Comment by AndruAlex** [comment]
с вертикальными фото какая то дичь 
поправлю потом если придумаю как
