### ISSUE TITLE
Правки. Статьи

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/ecoenergie#95]
- [x] Поровнять все по-человечески, как в макете
![image](https://cloud.githubusercontent.com/assets/11739563/13915322/a23ac746-ef5c-11e5-9a5d-3bb27567afb7.png)

- [x] криво 
![image](https://cloud.githubusercontent.com/assets/11739563/13915327/a724bdb6-ef5c-11e5-9d0c-fc7ad6a67541.png)

- [x] Внимательно изучить макет и сделать по макету 
![image](https://cloud.githubusercontent.com/assets/11739563/13915344/c1d4ef5a-ef5c-11e5-8dc3-c7b1bf6040d0.png)

- [x] В статье не отображаются картинки 
![image](https://cloud.githubusercontent.com/assets/11739563/13915422/3a234182-ef5d-11e5-83ad-bf8cfd536982.png)

- [x] нет нумерации статей

**Comment by AndruAlex** [comment]
я конечно не уверн но аоследние 2 пункта не ко мне относятся

**Comment by dadakax** [comment]
Вопрос, нахрена нужна нумерация статей?

**Comment by dadakax** [comment]
Что за нумерация статей?? Где, как и зачем?
